config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "coin#price"

  post "/compra", to: "coin#compra", as: :compra
  post "/venta", to: "coin#venta", as: :venta
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord

end

app/models/transaccion.rb
class Transaccion < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coin_controller.rb
class CoinController < ApplicationController

  def price
    api()
    informacion()
  end

  def compra
    @item = Transaccion.new(trans_params)
    if validacionCompra(@item.usuario, @item.pago, @item.cantidad)
        @item.save
        redirect_to root_path, notice: 'Registro creado exitosamente'
    else
      redirect_to root_path, alert: 'Error al crear el registro'
    end
  end

  def venta
    @item = Transaccion.new(trans_params)
    if validacionVenta(@item.usuario, @item.pago, @item.cantidad)
        @item.save
        redirect_to root_path, notice: 'Registro creado exitosamente'
    else
      redirect_to root_path, alert: 'Error al crear el registro'
    end
  end

  def api
    require 'uri'
    require 'net/http'

    url = URI("https://api.coingecko.com/api/v3/simple/price?vs_currencies=usd&ids=bitcoin&names=bitcoin&symbols=btc&precision=8")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(url)
    request["accept"] = 'application/json'
    request["x-cg-demo-api-key"] = 'CG-fYu9EpXujAQd4tan3SPmNQpb'

    response = http.request(request)
    puts response.read_body
    @bitcoin_data = JSON.parse(response.body)
    @price = @bitcoin_data["bitcoin"]["usd"]
  end

  def informacion
    @Tcompra = Transaccion.where(tipo: "Compra")
    @Tventa = Transaccion.where(tipo: "Venta")
    @usuario = Usuario.find(1)

  end

  private

  def trans_params

      params.permit(:usuario, :monedaR, :monedaE, :cantidad,:pago, :tipo, :precio)
  end

  def validacionCompra (usuario, pago, cantidad)
    @usuario = Usuario.find(usuario)
    @diferencia = @usuario.saldo - pago
    if @diferencia > 0
      @cartera = @usuario.cartera + cantidad
      @usuario.update(saldo: @diferencia, cartera: @cartera)
      return true
    end

  end

  def validacionVenta (usuario, pago, cantidad)
    @usuario = Usuario.find(usuario)
    @diferencia = @usuario.saldo + pago
    @cartera = @usuario.cartera - cantidad
    if @diferencia > 0 && @cartera > 0
      @usuario.update(saldo: @diferencia, cartera: @cartera)
      return true
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coin_helper.rb
module CoinHelper
end

app/views/coin/price.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>
<div class="bg-car rounded">
  <h1 class="fw-medium text-center">Precio del Bitcoin</h1>

  <h3 class="fw-medium">El precio actual es: <b>$<%= number_with_delimiter(@price, precision: 8 ) %> USD</b></h3>
</div>


<div class="row mt-3">
  <div class="col-lg-6">
    <div class="d-grid gap-2 m-1">
    <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#compra">
      Comprar
    </button>
    </div>
    <table class="table table-bordered table-striped table-hover">
       <thead>
        <tr>
          <th scope="col">Usuario</th>
          <th scope="col">Moneda a Comprar</th>
          <th scope="col">Cantidad</th>
          <th scope="col">Precio</th>
          <th scope="col">Moneda de pago</th>
          <th scope="col">Pago</th>
          <th scope="col">Fecha</th>
        </tr>
      </thead>
      <tbody>
          <% @Tcompra.each do |item| %>
          <tr>
            <td><%=item.usuario%></td>
            <td><%=item.monedaE%></td>
            <td><%=item.cantidad%></td>
            <td><%=item.precio%></td>
            <td><%=item.monedaR%></td>
            <td><%=item.pago%></td>
            <td><%=item.created_at.strftime("%d/%m/%Y")%></td>
          </tr>
          <% end %>

      </tbody>
    </table>
  </div>
  <div class="col-lg-6">
    <div class="d-grid gap-2 m-1">
    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#venta">
      Venta
    </button>
    <table class="table table-bordered table-striped table-hover ">
       <thead>
        <tr>
          <th scope="col">Usuario</th>
          <th scope="col">Moneda a Vender</th>
          <th scope="col">Cantidad</th>
          <th scope="col">Precio</th>
          <th scope="col">Moneda de pago</th>
          <th scope="col">Pago</th>
          <th scope="col">Fecha</th>
        </tr>
      </thead>
      <tbody>
          <% @Tventa.each do |item| %>
          <tr>
            <td><%=item.usuario%></td>
            <td><%=item.monedaE%></td>
            <td><%=item.cantidad%></td>
            <td><%=item.precio%></td>
            <td><%=item.monedaR%></td>
            <td><%=item.pago%></td>
            <td><%=item.created_at.strftime("%d/%m/%Y")%></td>
          </tr>
          <% end %>

      </tbody>
    </table>
  </div>
</div>




<!-- Modal Compra -->
<div class="modal fade" id="compra" tabindex="-1" aria-labelledby="compraLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="compraLabel">Modal C</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with(url: compra_path, method: :post) do |form| %>
          <div class="field">
          <%= form.label :"Usuario",class:"form-label" %>
          <%= form.collection_select :usuario, Usuario.all, :id, :nombre,{}, {class: "form-select"}  %>
          <%= form.label :"Moneda a Comprar",class:"form-label" %>
          <%=form.text_field :monedaE ,class:"form-control", value: "BTC", readonly: true%>
          <%= form.label :"Cantidad" %>
          <%= form.number_field :cantidad,class:"form-control", id: "cantidadC" %>
          <%= form.label :"precio" %>
          <%= form.number_field :precio,class:"form-control", value: @price%>
          <%= form.label :"Moneda de pago",class:"form-label" %>
          <%=form.text_field :monedaR ,class:"form-control", value: "USD", readonly: true%>
          <%= form.label :"Descuento",class:"form-label"%>
          <%=form.text_field :pago ,class:"form-control", id: "totalC"%>
          <%= form.label :"Tipo",class:"form-label"%>
          <%=form.text_field :tipo ,class:"form-control", value: "Compra", readonly: true%>
          </div>
          <%= form.submit "enviar", class: "m-3 btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Modal Compra -->

<!-- Modal Venta -->
<div class="modal fade" id="venta" tabindex="-1" aria-labelledby="ventaLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="MventaLabel">Modal V</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with(url: venta_path, method: :post) do |form| %>
          <div class="field">
          <%= form.label :"Usuario",class:"form-label" %>
          <%= form.collection_select :usuario, Usuario.all, :id, :nombre,{}, {class: "form-select"}  %>
          <%= form.label :"Moneda a Vender",class:"form-label" %>
          <%=form.text_field :monedaE ,class:"form-control", value: "BTC", readonly: true%>
          <%= form.label :"Cantidad" %>
          <%= form.number_field :cantidad,class:"form-control", id: "cantidadV" %>
          <%= form.label :"precio" %>
          <%= form.number_field :precio,class:"form-control", value: @price%>
          <%= form.label :"Moneda de Pago",class:"form-label" %>
          <%=form.text_field :monedaR ,class:"form-control", value: "USD", readonly: true%>
          <%= form.label :"Pago",class:"form-label"%>
          <%=form.text_field :pago ,class:"form-control", id: "totalV"%>
          <%= form.label :"Tipo",class:"form-label"%>
          <%=form.text_field :tipo ,class:"form-control", value: "Venta", readonly: true%>

          </div>
          <%= form.submit "enviar", class: "m-3 btn btn-primary" %>
        <% end %>
      </div>

    </div>
  </div>
</div>
<!-- Modal Venta -->





<script>
  function setupEventListeners() {
  let cantidadInputC = document.getElementById('cantidadC');
  let totalInputC = document.getElementById('totalC');
  let cantidadInputV = document.getElementById('cantidadV');
  let totalInputV = document.getElementById('totalV');
  // Escuchar cambios en ambos inputs
  [cantidadInputC].forEach(input => {
    input.addEventListener('input', calcularTotalC);
  });

  [cantidadInputV].forEach(input => {
    input.addEventListener('input', calcularTotalV);
  });

  function calcularTotalC() {
    let cantidad = parseFloat(cantidadInputC.value) || 0;
    let precio = parseFloat(<%="%.8f" % @price%>) || 0;
    totalInputC.value = (cantidad * precio).toFixed(2);
  }

  function calcularTotalV() {
    let cantidadV = parseFloat(cantidadInputV.value) || 0;
    let precioV = parseFloat(<%="%.8f" % @price%>) || 0;
    totalInputV.value = (cantidadV * precioV).toFixed(2);
  }
  }

  document.addEventListener('DOMContentLoaded', setupEventListeners);
  document.addEventListener('turbo:load', setupEventListeners);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bitcoin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  </head>

  <body class="bg">
    <nav class="navbar bg-dark ">
      <div class="container-fluid ">
      <a class="navbar-brand fw-semibold text-white" href="#">
        <img src="https://cdn-icons-png.flaticon.com/512/2157/2157572.png " alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
        BTC Compra y venta
      </a>
      <p class="navbar-brand text-white"><b>Usuario:</b> <%= @usuario.nombre %> | <b>Saldo Actual:</b> $<%= number_with_delimiter(@usuario.saldo, precision: 2 ) %> USD | <b>Cartera:</b> <%= "%.0f" % @usuario.cartera %> BTC</p>
      </div>
    </nav>
    <section class="m-5">
      <%= yield %>
    </section>
  </body>
</html>